package com.backend.visualcash.security.service;

import com.backend.visualcash.dto.UserInfo;
import com.backend.visualcash.security.entity.Usuario;
import com.backend.visualcash.security.repository.UsuarioRepository;
import java.io.UnsupportedEncodingException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.Optional;
import javax.mail.MessagingException;
import javax.mail.internet.MimeMessage;
import org.springframework.mail.javamail.JavaMailSender;
import org.springframework.mail.javamail.MimeMessageHelper;

@Service
@Transactional
public class UsuarioService {

    @Autowired
    UsuarioRepository usuarioRepository;

    @Autowired
    private JavaMailSender mailSender;
 
    public Optional<UserInfo> getUserInfo(String email){
        return usuarioRepository.getUserInfo(email);
    } 
    public Optional<Usuario> getByEmail(String email){
        return usuarioRepository.findByEmail(email);
    }
    public Usuario findByVerificationCodeAndEmailAndActive(String code, String email){
        return usuarioRepository.findByVerificationCodeAndEmail(code,email);  
    }
    public boolean existsByEmail(String email){
        return usuarioRepository.existsByEmail(email);
    }

    public void save(Usuario usuario){
        usuarioRepository.save(usuario);
    }
    
    public void register(Usuario usuario, String siteURL) throws UnsupportedEncodingException, MessagingException {
        save(usuario);        
        sendVerificationEmail(usuario, siteURL);
    }
    public void deleteById(int id){
        usuarioRepository.deleteById(id);
    }

    public boolean verify(String verificationCode) {
    Usuario usuario = usuarioRepository.findByVerificationCode(verificationCode);
    if (usuario == null || usuario.isActive()) {
        return false;
    } else {
        usuario.setVerificationCode(null);
        usuario.setActive(true);
        usuarioRepository.save(usuario);         
        return true;
    }
     
}
    public void sendVerificationEmail(Usuario usuario, String siteURL) throws MessagingException, UnsupportedEncodingException {
        
    String toAddress = usuario.getEmail();
    String fromAddress = "soporte@mivisualcash.com";
    String senderName = "VISUALCASH";
    String subject = "ACTIVACION DE CUENTA";
    String mensaje = "Haz click <a href='"+siteURL + "?code=" + usuario.getVerificationCode()+"'>aquí</a> para activar tu cuenta.<br><br>Si no se realiza la confirmación del correo durante las próximas 24 horas el registro será eliminado.";
    String content = "<html xmlns='http://www.w3.org/1999/xhtml' xmlns:v='urn:schemas-microsoft-com:vml' xmlns:o='urn:schemas-microsoft-com:office:office'>"
            + "<head>"
            + "<!--[if gte mso 15]>"
            + "<xml>"
            + "<o:OfficeDocumentSettings>"
            + "<o:AllowPNG></o:AllowPNG>"
            + "<o:PixelsPerInch>96</o:PixelsPerInch>"
            + "</o:OfficeDocumentSettings>"
            + "</xml>"
            + "<![endif]-->"
            + "<meta charset='UTF-8'>"
            + "<meta http-equiv='X-UA-Compatible' content='IE=edge'>"
            + "<meta name='viewport' content='width=device-width, initial-scale=1'>"
            + "<meta name='EditorVersion' content='1.0'>"
            + "<style type='text/css'>"
            + "td.moduloTexto,td.templateButtonContent,.templateTableExternal td,.templateTableExternal th{"
            + "/* These are technically the same, but use both */"
            + "/*overflow-wrap: break-word;"
            + "word-wrap: break-word;"
            + "-ms-word-break: break-all;*/"
            + "/* Adds a hyphen where the word breaks, if supported (No Blink) */"
            + "/*-ms-hyphens: auto;"
            + "-moz-hyphens: auto;"
            + "-webkit-hyphens: auto;"
            + "hyphens: auto;*/"
            + "}"
            + "/*"
            + "@tab Body"
            + "@section Imagen de Texto"
            + "*/"
            + ".moduloTexto img{"
            + "/*@editable*/padding-top:5px !important;"
            + "/*@editable*/padding-bottom:5px !important;"
            + "/*@editable*/padding-left:0px !important;"
            + "/*@editable*/padding-right:15px !important;"
            + "}"
            + "p{	margin:10px 0;padding:0;}"
            + "table{	border-collapse:collapse;}"
            + "h1,h2,h3,h4,h5,h6{"
            + "display:block;"
            + "margin:0;"
            + "padding:0;"
            + "img,a img{"
            + "border:0;"
            + "height:auto;"
            + "outline:none;"
            + "text-decoration:none;"
            + "max-width: 100%;"
            + "}"
            + "body{	margin:0;padding:0;}"
            + "#outlook a{padding:0;}"
            + "mg{-ms-interpolation-mode:bicubic;}"
            + "table{mso-table-lspace:0pt;mso-table-rspace:0pt;}"
            + ".ReadMsgBody{width:100%;}"
            + ".ExternalClass{width:100%;}"
            + "p,a,li,td,blockquote{mso-line-height-rule:exactly;}"
            + "a[href^=tel],a[href^=sms]{"
            + "color:inherit;"
            + "cursor:default;"
            + "text-decoration:none;"
            + "}"
            + "p,a,li,td,body,table,blockquote{"
            + "-ms-text-size-adjust:100%;"
            + "-webkit-text-size-adjust:100%;"
            + "}"
            + ".ExternalClass,.ExternalClass p,.ExternalClass td,.ExternalClass div,.ExternalClass span,.ExternalClass font{"
            + "line-height:100%;"
            + "}"
            + "a[x-apple-data-detectors]{"
            + "color:inherit !important;"
            + "text-decoration:none !important;"
            + "font-size:inherit !important;"
            + "font-family:inherit !important;"
            + "font-weight:inherit !important;"
            + "line-height:inherit !important;"
            + "}"
            + "/*"
            + "@tab Page"
            + "@section Heading "
            + "@tip Set the styling for all first-level headings in your emails. These should be the largest of your headings."
            + "@style heading 1"
            + "*/"
            + "h1,h1 *{"
            + "/*@editable*/color:#c1c1c1;"
            + "/*@editable*/font-family:arial,helvetica neue,helvetica,sans-serif;"
            + "/*@editable*/font-size:40px;"
            + "/*@editable*/font-style:normal;"
            + "/*@editable*/font-weight:bold;"
            + "/*@editable*/line-height:125%;"
            + "/*@editable*/letter-spacing:normal;"
            + "/*@editable*/text-align:left;"
            + "}"
            + "/*"
            + "@tab Page"
            + "@section Heading 2"
            + "@tip Set the styling for all second-level headings in your emails."
            + "@style heading 2"
            + "*/"
            + "h2,h2 *{"
            + "/*@editable*/color:#666666;"
            + "/*@editable*/font-family:arial,helvetica neue,helvetica,sans-serif;"
            + "/*@editable*/font-size:18px;"
            + "/*@editable*/font-style:normal;"
            + "/*@editable*/font-weight:bold;"
            + "/*@editable*/line-height:125%;"
            + "/*@editable*/letter-spacing:normal;"
            + "/*@editable*/text-align:left;"
            + "}"
            + "/*"
            + "@tab Page"
            + "@section Heading 3"
            + "@tip Set the styling for all third-level headings in your emails."
            + "@style heading 3"
            + "*/"
            + "h3,h3 *{"
            + "/*@editable*/color:#202020;"
            + "/*@editable*/font-family:Helvetica;"
            + "/*@editable*/font-size:20px;"
            + "/*@editable*/font-style:normal;"
            + "/*@editable*/font-weight:bold;"
            + "/*@editable*/line-height:125%;"
            + "/*@editable*/letter-spacing:normal;"
            + "/*@editable*/text-align:left;"
            + "}"
            + "/*"
            + "@tab Page"
            + "@section Heading 4"
            + "@tip Set the styling for all fourth-level headings in your emails. These should be the smallest of your headings."
            + "@style heading 4"
            + "*/"
            + "h4,h4 * {"
            + "/*@editable*/color:#202020;"
            + "/*@editable*/font-family:Helvetica;"
            + "/*@editable*/font-size:18px;"
            + "/*@editable*/font-style:normal;"
            + "/*@editable*/font-weight:bold;"
            + "/*@editable*/line-height:125%;"
            + "/*@editable*/letter-spacing:normal;"
            + "/*@editable*/text-align:left;"
            + "}"
            + "/*"
            + "@tab Page"
            + "@section Texto enlaces"
            + "@tip Set the style to the Links "
            + "@style Links"
            + "*/"
            + "a{"
            + "/*@editable*/text-decoration:none;"
            + "}"
            + "/**"
            + "@tab Page"
            + "@section Fondo del email"
            + "*/"
            + "body,#teExternalBody{"
            + "/*@editable*/background-color:#000000;"
            + "height: 100%;"
            + "width: 100%;"
            + "}"
            + "/**"
            + "@tab Page"
            + "@section Márgenes externos"
            + "*/"
            + "td.teExternalBody{"
            + "/*@editable*/padding-top:20px;"
            + "/*@editable*/padding-bottom:20px;"
            + "}"
            + "/*"
            + "@tab Body"
            + "@section Texto"
            + "*/"
            + "td.moduloTexto,#teExternalBody{"
            + "/*@editable*/color:#999999;"
            + "/*@editable*/font-family:arial,helvetica neue,helvetica,sans-serif;"
            + "/*@editable*/font-size:14px;"
            + "/*@editable*/font-style:normal;"
            + "/*@editable*/font-weight:normal;"
            + "/*@editable*/letter-spacing:normal;"
            + "}"
            + "p,div,span{"
            + "line-height:normal;"
            + "}"
            + ""
            + "/*"
            + "@tab Body"
            + "@section Fondo del cuerpo"
            + "*/"
            + "#teInternalBody{"
            + "/*@editable*/max-width:650px !important;"
            + "/*@editable*/border-style:none;"
            + "/*@editable*/border-color:#000000;"
            + "/*@editable*/border-width: 1px;"
            + "/*@editable*/background-color:#000000;	"
            + "}"
            + "/**"
            + "@tab Body"
            + "@section Margen del cuerpo"
            + "*/"
            + "td.teInternalBody{"
            + "/*@editable*/padding-top: 20px;"
            + "/*@editable*/padding-bottom: 0;"
            + "/*@editable*/padding-left: 20px;"
            + "/*@editable*/padding-right: 20px;"
            + "}"
            + "/**"
            + " * @tab Body"
            + " * @section Margen de textos"
            + " */"
            + "td.moduloTexto{"
            + "/*@editable*/padding-top:10px;"
            + "/*@editable*/padding-bottom:10px;"
            + "/*@editable*/padding-left:10px;"
            + "/*@editable*/padding-right:10px;"
            + "}"
            + "@media only screen and (max-width: 480px){"
            + "img.te-responsive, .video img{ width: 100% !important;}"
            + "img{max-width: 100%;}"
            + ".mobileWidth,.contenedorbasecabecera,.contenedorbasepie{"
            + " width:100% !important;"
            + "}"
            + "/*"
            + "@tab Mobile Styles"
            + "@section Heading 1"
            + "@tip Make the first-level headings larger in size for better readability on small screens."
            + "*/"
            + "h1,h1 *{"
            + "/*@editable*/font-size:22px !important;"
            + "/*@editable*/line-height:125% !important;"
            + "}"
            + "/*"
            + "@tab Mobile Styles"
            + "@section Heading 2"
            + "@tip Make the second-level headings larger in size for better readability on small screens."
            + "*/"
            + "h2,h2 *{"
            + "/*@editable*/font-size:20px !important;"
            + "/*@editable*/line-height:125% !important;"
            + "}"
            + "/*"
            + "@tab Mobile Styles"
            + "@section Heading 3"
            + "@tip Make the third-level headings larger in size for better readability on small screens."
            + "*/"
            + "h3,h3 *{"
            + "/*@editable*/font-size:18px !important;"
            + "/*@editable*/line-height:125% !important;"
            + "}"
            + "/*"
            + "@tab Mobile Styles"
            + "@section Heading 4"
            + "@tip Make the fourth-level headings larger in size for better readability on small screens."
            + "*/"
            + "h4,h4 *{"
            + "/*@editable*/font-size:16px !important;"
            + "/*@editable*/line-height:150% !important;"
            + "}"
            + ".columnWrapper,.columnWrapper .sortable-module,table.contenedorbasepie,table.contenedorbasecabecera{"
            + "display:block;"
            + "float: left;/*correccion cliente nativo Android superiores a 480px*/"
            + "width:100% !important;"
            + "padding-left:0 !important;"
            + "padding-right: 0 !important;"
            + "}"
            + "}"
            + "/**"
            + "* @tab Columnas"
            + "* @section 1 Columnas"
            + "* @module module-content 1col_b"
            + "*/"
            + "td.column100{"
            + "/*@editable*/padding-top:0;"
            + "/*@editable*/padding-bottom:20px;"
            + "/*@editable*/padding-left:0;"
            + "/*@editable*/padding-right:0;"
            + "}"
            + "/**"
            + "* @tab Columnas"
            + "* @section 2 Columnas 66-33 - Columna 66%"
            + "* @module module-content 2cols6633_a"
            + "*/"
            + "table.templateColumns6633 td.column66{"
            + "/*@editable*/width:66%;"
            + "/*@editable*/padding-top:0;"
            + "/*@editable*/padding-bottom:20px;"
            + "/*@editable*/padding-left:60px;"
            + "/*@editable*/padding-right:13.5px;"
            + "}"
            + "/**"
            + "* @tab Columnas"
            + "* @section 2 Columnas 66-33 - Columna 33%"
            + "* @module module-content 2cols6633_b"
            + "*/"
            + "table.templateColumns6633 td.column33{"
            + "/*@editable*/width:33%;"
            + "/*@editable*/padding-top:0;"
            + "/*@editable*/padding-bottom:20px;"
            + "/*@editable*/padding-left:6.5px;"
            + "/*@editable*/padding-right:0;"
            + "}"
            + "/**"
            + "* @tab Columnas"
            + "* @section Fondo bloque completo"
            + "* @module module-content 2cols_d"
            + " */"
            + "table.templateColumns{"
            + "/*@editable*/background-color:#000000;"
            + "}"
            + "/**"
            + "* @tab Columnas"
            + "* @section Márgenes bloque completo"
            + "* @module module-content 2cols_c"
            + "*/"
            + "td.templateColumns{"
            + "/*@editable*/padding-top:0;"
            + "/*@editable*/padding-bottom:0;"
            + "/*@editable*/padding-left:0;"
            + "/*@editable*/padding-right:0;"
            + "/**"
            + "* @tab Columnas"
            + "* @section 1 Columnas"
            + "* @module module-content 1col_a"
            + "*/"
            + "td.column100{"
            + "/*@editable*/padding-top:0;"
            + "/*@editable*/padding-bottom:20px;"
            + "/*@editable*/padding-left:0;"
            + "/*@editable*/padding-right: 0;"
            + "}"
            + "/**"
            + "@tab Botones"
            + "@section Márgenes del botón"
            + "@module button_0"
            + "*/"
            + "table.templateButtonExternal{"
            + "width:100%;"
            + "}"
            + "/**"
            + "@tab Botones"
            + "@section Márgenes del botón"
            + "@module button_a"
            + "*/"
            + "td.templateButtonExternal{"
            + "/*@editable*/padding-top:20px;"
            + "/*@editable*/padding-bottom:20px;"
            + "/*@editable*/padding-left:0;"
            + "/*@editable*/padding-right:0;"
            + "}"
            + "/**"
            + "@tab Botones"
            + "@section Relleno del botón"
            + "@module button_b"
            + "*/"
            + "table.templateButton{"
            + "/*@editable*/background-color:#CBCBCB;"
            + "/*@editable*/border-radius:4px;"
            + "/*@editable*/border-width:1px;"
            + "/*@editable*/border-color:#CBCBCB;"
            + "/*@editable*/width:auto;"
            + "border-style: none;"
            + "border-collapse:separate !important;"
            + "}"
            + "/**"
            + "@tab Botones"
            + "@section Texto del botón"
            + "@module button_c"
            + "*/"
            + "table.templateButton td.templateButtonContent{"
            + "/*@editable*/padding-top:15px;"
            + "/*@editable*/padding-bottom:15px;"
            + "/*@editable*/padding-left:15px;"
            + "/*@editable*/padding-right:15px;"
            + "/*@editable*/text-align:center;"
            + "}"
            + "/**"
            + "@tab Botones"
            + "@section Texto del botón"
            + "@module button_d"
            + "*/"
            + "table.templateButton td.templateButtonContent a{"
            + "/*@editable*/color:#585858;"
            + "/*@editable*/font-family:Arial;"
            + "/*@editable*/font-size:14px;"
            + "/*@editable*/font-style:normal;"
            + "/*@editable*/font-weight:bold;"
            + "/*@editable*/line-height:100%;"
            + "/*@editable*/letter-spacing:normal;"
            + "/*@editable*/text-decoration:none;"
            + "}"
            + "/**"
            + "@tab Tabla"
            + "@section Comportamiento del Border"
            + "@module table_a"
            + "*/"
            + "table.templateTable{"
            + "/*@editable*/border-collapse: collapse;"
            + "}"
            + "@tab Tabla"
            + "@section Border"
            + "@module table_b"
            + "*/"
            + "table.templateTable,table.templateTable td,table.templateTable th{"
            + "/*@editable*/border-width:1px;"
            + "/*@editable*/border-color:#000000;"
            + "/*@editable*/border-style:solid;"
            + "}"
            + "@tab Tabla"
            + "@section Cabecera - th"
            + "@module table_c"
            + "*/"
            + "table.templateTable th {"
            + "/*@editable*/padding-top:5px;"
            + "/*@editable*/padding-bottom:5px;"
            + "/*@editable*/padding-left:5px;"
            + "/*@editable*/padding-right:5px;"
            + "/*@editable*/padding-top:5px;"
            + "/*@editable*/text-align: center;"
            + "/*@editable*/background-color:#dddddd;"
            + "}"
            + "/**"
            + "@tab Tabla"
            + "@section Texto Cabecera - th"
            + "@module table_c_a"
            + "*/"
            + "table.templateTable th div{"
            + "/*@editable*/color:#000000;"
            + "/*@editable*/font-family:Arial;"
            + "/*@editable*/font-size:12px;"
            + "/*@editable*/font-style:normal;"
            + "/*@editable*/font-weight:normal;"
            + "/*@editable*/line-height:100%;"
            + "/*@editable*/letter-spacing:normal;"
            + "/*@editable*/text-decoration:none;"
            + "}"
            + "/**"
            + "@tab Tabla"
            + "@section Celdas - td"
            + "@module table_d_a"
            + "*/"
            + "table.templateTable td {"
            + "/*@editable*/padding-top:5px;"
            + "/*@editable*/padding-bottom:5px;"
            + "/*@editable*/padding-left:5px;"
            + "/*@editable*/padding-right:5px;"
            + "/*@editable*/padding-top:5px;"
            + "/*@editable*/background-color:#ffffff;"
            + "/*@editable*/text-align:left;"
            + "}"
            + "/**"
            + "@tab Tabla"
            + "@section Texto Celdas - td"
            + "@module table_d_b"
            + "*/"
            + "table.templateTable td div{"
            + "/*@editable*/color:#bbbbbb;"
            + "/*@editable*/font-family:Arial;"
            + "/*@editable*/font-size:12px;"
            + "/*@editable*/font-style:normal;"
            + "/*@editable*/font-weight:normal;"
            + "/*@editable*/line-height:100%;"
            + "/*@editable*/letter-spacing:normal;"
            + "/*@editable*/text-decoration:none;"
            + "}"
            + "@tab Body"
            + "@section Fondo del texto"
            + "@module text_background_0"
            + "*/"
            + "td.moduloTexto{"
            + "/*@editable*/border-width:0px;"
            + "border-collapse:collapse;"
            + "/*@editable*/border-style:none;"
            + "/*@editable*/border-color:#cccccc;"
            + "/*@editable*/background-color:transparent;"
            + "</style>"
            + "</head>"
            + "<body>"
            + "<center>"
            + "<table id='teExternalBody' border='0' cellpadding='0' cellspacing='0' align='center' height='100%' width='100%'>"
            + "<tbody>"
            + "<tr>"
            + "<td class='teExternalBody' align='center' valign='top'>"
            + "<!-- BEGIN TEMPLATE // -->"
            + "<!--[if (gte mso 9)|(IE)]>"
            + "<table align='center' border='0' cellspacing='0' cellpadding='0' width='650' style='width:650px;'>"
            + "<tr>"
            + "<td align='center' valign='top' width='650' style='width:650px;'>"
            + "<![endif]-->"
            + "<table id='teInternalBody' border='0' cellpadding='0' cellspacing='0' width='100%'>"
            + "<tbody>"
            + "<tr>"
            + "<td class='teInternalBody'>"
            + "	<table id='teContainerBody' border='0' cellpadding='0' cellspacing='0' width='100%'>"
            + "	<tbody class='ui-sortable' te-draggablecontainer='' style=''>"
            + "<tr class='1col finalmodule' te-draggable='' te-repeatable='' style=''>"
            + " <td class='teRelative'>"
            + "<table class='templateColumns templateColumns100' width='100%' cellpadding='0' cellspacing='0' border='0' style='border-radius:0;border-width:0;border-color:inherit;background-color:inherit;'>"
            + "<tbody>"
            + "<tr>"
            + "<td width='100%' valign='top' class='templateColumns'>"
            + "<table align='center' border='0' cellspacing='0' cellpadding='0' width='100%' style='width:100%;'>"
            + "<tbody>"
            + "<tr>"
            + "<td align='center' valign='top' class='columnWrapper column100 sortable-module ui-sortable'>"
            + "<div class='image finalelement ' te-repeatable='' te-draggable=''>"
            + "<table width='100%' data-responsive='true' data-resize='false' cellpadding='0' cellspacing='0' border='0'>"
            + "<tbody>"
            + "<tr>"
            + "<td width='100%' align='center' valign='middle' style='line-height: 0 !important;'>"
            + "<a href='https://www.teenvio.com' target='_blank'><img align='' te-edit='left_column_image' class='columnImage te-responsive' alt='' src='https://mastervirt1.teenvio.com/v3/uploads/visualcash/gestor-imagenes/final_89101620762971.png' width='610' style='' data-link='https://www.teenvio.com'"
            + "</td>"
            + "</tr>"
            + "</tbody>"
            + "</table>"
            + "</div>"
            + "<div class='text finalelement' te-draggable='' te-repeatable=''>"
            + "<table width='100%' cellpadding='0' cellspacing='0' border='0'>"
            + "<tbody>"
            + "<tr>"
            + "<td width='100%' style='background-color: none;' te-edit='' class='moduloTexto'>"
            + "<!-- align='left' -->"
            + "<div>"
            + "<h1 style=''>ACTIVACION DE CUENTA</h1>"
            + "<p>"+mensaje+"</p>"
            + "</div>"
            + "</td>"
            + "</tr>"
            + "</tbody>"
            + "</table>"
            + "</div>"
            + "</td>"
            + "</tr>"
            + "</tbody>"
            + "</table>"
            + "</td>"
            + "	"
            + "													</tr>"
            + "															</tbody>"
            + "														</table>"
            + "													</td>"
            + "												</tr>"
            + "												<tr class='2cols_66_33 finalmodule' te-draggable='' style=''>"
            + "													<td class='teRelative'>"
            + "														<table class='templateColumns templateColumns6633' width='100%' cellpadding='0' cellspacing='0' border='0' style=''>"
            + "															<tbody>"
            + "																<tr te-repeatable=''>"
            + "																	<td width='100%' valign='top' class='templateColumns'>"
            + "																		<table align='center' border='0' cellspacing='0' cellpadding='0' width='100%' style='width:100%;'>"
            + "																			<tbody>"
            + "																				<tr>"
            + "																					<td align='center' valign='top' class='columnWrapper column column66 sortable-module ui-sortable'>"
            + "<div class='text finalelement ' te-repeatable='' style='position: relative; left: 0px; top: 0px;'>"
            + "<table border='0' cellpadding='0' cellspacing='0' width='100%'>"
            + "																								<tbody>"
            + "																									<tr>"
            + "																										<td style='' te-edit='' class='moduloTexto' align='left' width='100%'><span style='font-size: 12px; color: rgb(255, 255, 255); font-weight: bold;'>www.mivisualcash.com</span></td>"
            + "																									</tr>"
            + "																								</tbody>"
            + "																							</table>"
            + "																						</div>"
            + "																					</td>"
            + "																					<td align='center' valign='top' class='columnWrapper column column33 sortable-module ui-sortable'>"
            + "</td>"
            + "																				</tr>"
            + "																			</tbody>"
            + "																		</table>"
            + "																	</td>	"
            + "														</tr>"
            + "															</tbody>"
            + "														</table>"
            + "													</td>"
            + "												</tr>"
            + "											</tbody>"
            + "										</table>"
            + "									</td>"
            + "								</tr>"
            + "</tbody>"
            + "						</table>"
            + "						<!--[if (gte mso 9)|(IE)]>"
            + "						</td>"
            + "						</tr>"
            + "						</table>"
            + "						<![endif]-->"
            + "					</td>"
            + "				</tr>"
            + "			</tbody>"
            + "		</table>"
            + "	</center>"
            + "</body>"
            + "</html>";
     
    MimeMessage message = mailSender.createMimeMessage();
    MimeMessageHelper helper = new MimeMessageHelper(message);
     
    helper.setFrom(fromAddress, senderName);
    helper.setTo(toAddress);
    helper.setSubject(subject);
    helper.setReplyTo("soporte@mivisualcash.com", "VISUALCASH");
    String verifyURL = siteURL + "/verify?code=" + usuario.getVerificationCode();
     
    content = content.replace("[[URL]]", verifyURL);
     
    helper.setText(content, true);
    
    mailSender.send(message);
    }
}
